version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - '443:443'
    volumes:
      - /home/anclarma/data/wp:/var/www/html
    env_file:
      - .env
    networks:
      - backend
    restart: on-failure
  mysql:
    build: ./mariadb
    ports:
      - '3306'
    volumes:
#      - /home/anclarma/data/db:/var/lib/mysql
      - /var/lib/mysql
    env_file:
      - .env
    networks:
      - backend
    restart: on-failure
  wordpress:
    build: ./wordpress
    ports:
      - '9000'
    volumes:
      - /home/anclarma/data/wp:/var/www/html
    env_file:
      - .env
    networks:
      - backend
    restart: on-failure
networks:
  backend:
    driver: bridge
