version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - '443:443'
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    networks:
      - backend
    restart: on-failure
  mysql:
    build: ./mariadb
    ports:
      - '3306'
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - backend
    restart: on-failure
  wordpress:
    build: ./wordpress
    ports:
      - '9000'
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    networks:
      - backend
    restart: on-failure

networks:
  backend:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/anclarma/data/db"
  wp:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/anclarma/data/wp"
